name: App Build

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - name: Setup Java
        uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3 # tag=v3
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - name: Assemble debug APKs
        run: ./gradlew --build-cache --no-daemon --info assembleDebug
      - name: Upload artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        with:
          name: build-artifacts
          retention-days: 14
          if-no-files-found: error
          path: app/build/outputs/apk/debug/*.apk
