name: Gradle validate

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**/gradl–µ-wrapper.jar'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b # tag=v1
